<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="KalkulatorBackend\**\*.cs" />
    <Content Remove="KalkulatorBackend\**\*" />
    <EmbeddedResource Remove="KalkulatorBackend\**\*" />
    <None Remove="KalkulatorBackend\**\*" />
  </ItemGroup>

</Project>